version: '3'

services:
    db:
        image: postgres:16-alpine
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
            - '5432:5432'
        volumes:
            - postgres13:/var/lib/postgresql/data
    redis:
        image: redis:7.0.15-alpine
        ports:
        - '6379:6379'
        volumes:
        - redis_data:/data
    test:
        build:
            context: .
            dockerfile: Dockerfile.dev
        command: bundle exec rspec
        volumes:
            - .:/rails
            - bundler_gems:/usr/local/bundle/
        depends_on:
            - db
            - redis 
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/store_development
            - REDIS_URL=redis://redis:6379/0
            - TEST_DATABASE_URL=postgresql://postgres:password@db:5432/store_test
volumes:
    postgres13:
    redis_data:
    bundler_gems:
